const seedRestaurants = [
  {
    _id: 'rest_pizza_01',
    id: 'rest_pizza_01',
    name: 'Gadbad Gourmet Pizza',
    description: 'Wood-fired artisanal speed pizzas baked for champions.',
    rating: 4.8,
    cuisine: 'Italian & Pizza',
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=500&q=80',
    isAvailable: true,
    prepTimeMinutes: 12,
  },
  {
    _id: 'rest_samosa_02',
    id: 'rest_samosa_02',
    name: 'Speedy Samosa & Chai',
    description: 'Crispy street-side delights delivered at lightning speed.',
    rating: 4.7,
    cuisine: 'Street Food & Snacks',
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&q=80',
    isAvailable: true,
    prepTimeMinutes: 8,
  },
  {
    _id: 'rest_biryani_03',
    id: 'rest_biryani_03',
    name: 'Biryani Bullet',
    description: 'Authentic slow-cooked dum biryani on high-speed wheels.',
    rating: 4.9,
    cuisine: 'Hyderabadi & Mughlai',
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=500&q=80',
    isAvailable: true,
    prepTimeMinutes: 15,
  },
  {
    _id: 'rest_dosa_04',
    id: 'rest_dosa_04',
    name: 'Dosa Drift & Idli Apex',
    description: 'Crispy golden dosas with roaring coconut chutneys.',
    rating: 4.6,
    cuisine: 'South Indian',
    imageUrl: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=500&q=80',
    isAvailable: true,
    prepTimeMinutes: 10,
  },
];

const seedMenuItems = [
  // Gadbad Gourmet Pizza
  {
    _id: 'item_pizza_01',
    id: 'item_pizza_01',
    restaurantId: 'rest_pizza_01',
    name: 'Truffle Turbo Pizza',
    description: 'Hand-tossed dough with wild mushrooms, truffle oil, and mozzarella.',
    price: 380,
    category: 'Pizza',
    imageUrl: 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=500&q=80',
    isAvailable: true,
  },
  {
    _id: 'item_pizza_02',
    id: 'item_pizza_02',
    restaurantId: 'rest_pizza_01',
    name: 'Nitro Pepperoni Pie',
    description: 'Loaded spicy pepperoni with roasted bell peppers and spicy chili honey.',
    price: 340,
    category: 'Pizza',
    imageUrl: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=500&q=80',
    isAvailable: true,
  },
  {
    _id: 'item_pizza_03',
    id: 'item_pizza_03',
    restaurantId: 'rest_pizza_01',
    name: 'Garlic Velocity Knots',
    description: 'Buttery roasted garlic knots served with warm marinara dipping sauce.',
    price: 150,
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1573821663912-569905455b1c?w=500&q=80',
    isAvailable: true,
  },
  // Speedy Samosa & Chai
  {
    _id: 'item_samosa_01',
    id: 'item_samosa_01',
    restaurantId: 'rest_samosa_02',
    name: 'Crispy Aloo Samosa Duo',
    description: 'Golden fried triangular pastries filled with spicy spiced potatoes & peas.',
    price: 80,
    category: 'Snacks',
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&q=80',
    isAvailable: true,
  },
  {
    _id: 'item_samosa_02',
    id: 'item_samosa_02',
    restaurantId: 'rest_samosa_02',
    name: 'Masala Chai Rocket Flask',
    description: 'Brewed with cardamom, ginger, and cinnamon. Stays steaming hot on the track!',
    price: 60,
    category: 'Beverages',
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&q=80',
    isAvailable: true,
  },
  {
    _id: 'item_samosa_03',
    id: 'item_samosa_03',
    restaurantId: 'rest_samosa_02',
    name: 'Paneer Tikka Roll',
    description: 'Smoky grilled cottage cheese rolled in flaky flatbread with mint chutney.',
    price: 190,
    category: 'Rolls',
    imageUrl: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=500&q=80',
    isAvailable: true,
  },
  // Biryani Bullet
  {
    _id: 'item_biryani_01',
    id: 'item_biryani_01',
    restaurantId: 'rest_biryani_03',
    name: 'Dum Biryani Championship Bowl',
    description: 'Aromatic basmati rice layered with fragrant spices, caramelized onions & herbs.',
    price: 290,
    category: 'Biryani',
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=500&q=80',
    isAvailable: true,
  },
  {
    _id: 'item_biryani_02',
    id: 'item_biryani_02',
    restaurantId: 'rest_biryani_03',
    name: 'Gulab Jamun Pitstop (2 pcs)',
    description: 'Warm soft dough dumplings soaked in rose-flavored saffron syrup.',
    price: 100,
    category: 'Dessert',
    imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=500&q=80',
    isAvailable: true,
  },
  // Dosa Drift
  {
    _id: 'item_dosa_01',
    id: 'item_dosa_01',
    restaurantId: 'rest_dosa_04',
    name: 'Ghee Roast Masala Dosa',
    description: 'Super thin golden crepe roasted in pure ghee, stuffed with spiced potato mash.',
    price: 160,
    category: 'Dosa',
    imageUrl: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=500&q=80',
    isAvailable: true,
  },
  {
    _id: 'item_dosa_02',
    id: 'item_dosa_02',
    restaurantId: 'rest_dosa_04',
    name: 'Button Idli Speed Bowl',
    description: '14 miniature steamed rice cakes dunked in hot piping sambar with podi butter.',
    price: 110,
    category: 'Breakfast',
    imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=500&q=80',
    isAvailable: true,
  },
];

module.exports = {
  seedRestaurants,
  seedMenuItems,
};
